name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Make a non-monotonic change to a file
    - name: Modify a file
      run: |
        RANDOM_NUMBER=$((RANDOM % 1000))
        echo "Random update: $RANDOM_NUMBER on $(date)" >> auto_commit_log.txt

    # Step 3: Configure Git and commit
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add auto_commit_log.txt
        git commit -m "Randomized commit on $(date): $RANDOM_NUMBER"
        git push
